[package]
name = "cef-rs-osr-sample"
version = "0.1.0"
edition = "2024"

[dependencies]
cef = { workspace = true }
softbuffer = "0.4.6" # for osr
winit = "0.30.12"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.1"
